apiVersion: v1
kind: Service
metadata:
  name: my-service2
spec:
  type: LoadBalancer
  loadBalancerIP: a36cc12022e5f4440805c9b9cc5bf390-2063831906.us-east-1.elb.amazonaws.com
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: my-app2
